source "https://api.berkshelf.com"

metadata

# Core server cookbooks
cookbook 'locale', git: 'https://github.com/hw-cookbooks/locale'
cookbook "apt"
cookbook 'build-essential'

# App server cookbooks
cookbook 'rvm', :git => 'https://github.com/fnichol/chef-rvm'
cookbook 'postgresql', github: "phlipper/chef-postgresql"

# Frontend
cookbook 'nodejs', github: "mdxp/nodejs-cookbook"
cookbook 'npm', git: "https://github.com/balbeko/chef-npm.git"

# on local path
cookbook 'basic', path: 'cookbooks/basic'
cookbook 'postgresql-locale-fix', path: 'cookbooks/postgresql-locale-fix'
cookbook 'frontend', path: 'cookbooks/frontend'
