source 'https://rubygems.org'

gem 'berkshelf', '~> 3.1.3', git: "git://github.com/berkshelf/berkshelf.git"

group :development do
  gem "vagrant", github: "mitchellh/vagrant"
end

group :plugins do
	gem 'vagrant-vbguest'
  gem "vagrant-berkshelf", github: "berkshelf/vagrant-berkshelf"
  gem "vagrant-omnibus", github: "schisamo/vagrant-omnibus"
end
