source 'https://rubygems.org'

gem 'berkshelf', '~> 3.1.4'

# gem 'knife-solo', '0.4.2'
# gem 'chef', '~> 11.12.8'
# gem 'chef-zero', '2.0.2'

# gem 'chef'
# gem 'knife-solo'
# gem "vagrant-omnibus"
# gem 'vagrant-cachier'
# gem "librarian-chef"

# gem 'knife-solo'
# gem 'vagrant', github: "mitchellh/vagrant"
# gem 'vagrant-omnibus'
# gem 'librarian-chef'

# Uncomment these lines if you want to live on the Edge:

# group :development do
#   gem "berkshelf", github: "berkshelf/berkshelf"
#   gem "vagrant", github: "mitchellh/vagrant"
# end

gem 'vagrant-vbguest'

group :plugins do
  gem "vagrant", github: "mitchellh/vagrant"
  gem "vagrant-berkshelf", github: "berkshelf/vagrant-berkshelf"
  gem "vagrant-omnibus", github: "schisamo/vagrant-omnibus"
end

