source 'https://rubygems.org'

# gem 'berkshelf'

# gem 'chef'
# gem 'knife-solo'
# gem "vagrant-omnibus"
# gem 'vagrant-cachier'
# gem "librarian-chef"

# gem 'knife-solo'
# gem 'vagrant', github: "mitchellh/vagrant"
# gem 'vagrant-omnibus'
# gem 'librarian-chef'

# Uncomment these lines if you want to live on the Edge:

group :development do
  gem "berkshelf", github: "berkshelf/berkshelf"
  gem "vagrant", github: "mitchellh/vagrant"
end

group :plugins do
  gem "vagrant-berkshelf", github: "berkshelf/vagrant-berkshelf"
  gem "vagrant-omnibus", github: "schisamo/vagrant-omnibus"
end

